Loading python/3.8.13/slu6jvw
  Loading requirement: bzip2/1.0.8/xipsq2f libmd/1.0.4/sioeueg
    libbsd/0.11.5/gdafde7 expat/2.4.8/5wnje43 ncurses/6.2/pqxvmoe
    readline/8.1/52qiwcn gdbm/1.23/lkx5uz6 libiconv/1.16/lr5guq5
    xz/5.2.5/khdza45 zlib/1.2.12/bsohwcg libxml2/2.9.13/f5kumg5 pigz/2.7/zay4a5o
    zstd/1.5.2/jvujieu tar/1.34/4cnckqw gettext/0.21/hgt6t5w
    libffi/3.4.2/svyohlf openssl/1.1.1o/bowp5gw sqlite/3.38.5/ulzkiln
    util-linux-uuid/2.37.4/nlecwm6
Traceback (most recent call last):
  File "autos_eval.py", line 180, in <module>
    main()
  File "autos_eval.py", line 121, in main
    df = pd.read_csv('trainers/model_logs.csv')
  File "/home/okcava/projects/universal_advex/.venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/okcava/projects/universal_advex/.venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/okcava/projects/universal_advex/.venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/okcava/projects/universal_advex/.venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/okcava/projects/universal_advex/.venv/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'trainers/model_logs.csv'
